spring.application.name=restApi

# Changed mySql to mysql
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb

# Changed .name to .username
spring.datasource.username=root

# Leave blank if your MySQL root user genuinely has no password,
# otherwise enter it here.
spring.datasource.password=asiqulx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true